### PR TITLE
3.5.1 release

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
I'm creating this PR in anticipation of the eventual merge when we release 3.5.1.

We can use the PR to keep track of discussions, todos, etc.

**Comment by slinkydeveloper** [comment]
We should merge #254 into this one

**Comment by vietj** [comment]
let's merge #254 into master and then we'll remerge this one into master or rebase it before

**Comment by jponge** [comment]
Just do what I did already: merge from master to that branch without fast
forward. Rebasing breaks cloned.

**Comment by slinkydeveloper** [comment]
I've updated 3.5.1 blog post with vertx-web-api-contract major changes/enhancements

**Comment by slinkydeveloper** [comment]
@vietj should I write some words about new methods of core websocket `close(short)` and `close(short, String)`?

**Comment by vietj** [comment]
we reverted it @slinkydeveloper because it only applies to websockets and the status code and reason don't make sense for other impls

**Comment by jponge** [comment]
🚀

**Pull request merged**
