### PR TITLE
vertx3 says hello to NPM users

### PR DESCRIPTION
**Pull request by pmlopes**
A blog post about NPM integration

### CODE REVIEW

**Comment by purplefox** [comment]
Looks good. I won't merge it now, in case you don't want it live yet. Just merge it when you want :)

**Comment by cescoffier** [comment]
It can be merged, and made public by removing the `draft: true` header.

**Comment by cescoffier** [comment]
This has been merged no ?

**Comment by pmlopes** [comment]
Yes

**Pull request closed without merging**
