### PR TITLE
New article about microservice and Vert.x

### PR DESCRIPTION
**Pull request by piomin**
I would like to publish my previous article about Vert.x available here: https://piotrminkowski.wordpress.com/2017/08/24/asynchronous-microservices-with-vert-x/

### CODE REVIEW

**Comment by vietj** [comment]
@piomin the article is very nice, I will rephrase some parts if you don't mind before publishing

**Comment by piomin** [comment]
Hi,
Ok. Thanks:)
Regards,
Piotr

20 wrz 2017 09:48 "Julien Viet" <notifications@github.com> napisał(a):

**Comment by piomin** [comment]
Hello, have you already rephrased those sentences?

**Comment by vietj** [comment]
In your project have you tried to use the codegen depenpency with the _processor_ classifier ? it allows to avoid the declaration of the annotation processor in pom.xml

**Comment by vietj** [comment]
@piomin here is the branch for the rework https://github.com/vert-x3/vertx-web-site/tree/piomin-piomin - can you try in your project to use the _processor_ classifier in your project and update it, so we can remove the speicific annotation processor declaration in pom.xml ?

**Comment by piomin** [comment]
We can close it

**Pull request closed without merging**
