### PR TITLE
Blog post: Simplified database transaction management with the Vert.x…

### PR DESCRIPTION
**Pull request by tsegismont**
… RxJava API

### CODE REVIEW

**Comment by tsegismont** [comment]
@jponge can you please take a look? Thank you

**Comment by vietj** [comment]
it would be good to publish early next week

**Comment by tsegismont** [comment]
Yeah I thought about Monday morning US eastern time

**Comment by tsegismont** [comment]
@jponge what do you mean?

**Comment by jponge** [comment]
@tsegismont I was just suggesting adding a point to close the item list :-)

**Comment by tsegismont** [comment]
Haaaa :bulb: :wink: 

Otherwise you're fine with the content?

**Comment by jponge** [comment]
Oh yes, the content is great Thomas!

**Comment by tsegismont** [comment]
@jponge done

**Comment by tsegismont** [comment]
@jponge perfect, thanks for reviewing!

**Comment by vietj** [comment]
good job guys!

**Pull request merged**
