### PR TITLE
added www.ilanus.com logo

### PR DESCRIPTION
**Pull request by mtorak**
Would you please add my logo to your "Who is using vert.x" page.
Thank you very much.

### CODE REVIEW

**Comment by cescoffier** [comment]
The logo needs to be "white on transparent". check how are made the other logos:
https://github.com/vert-x3/vertx-web-site/tree/master/src/site/assets/user_logos

**Comment by mtorak** [comment]
OK i'll be sending it as white on trans.

**Comment by michel-kraemer** [comment]
@mtorak any progress on this one?

**Comment by michel-kraemer** [comment]
No feedback from the original poster. @mtorak If you still want to add your logo then let us know. We'll be more than happy to do it.

**Pull request closed without merging**
