### PR TITLE
Tutorial of Vert.x blueprint - todo backend

### PR DESCRIPTION
**Pull request by sczyh30**
A tutorial blog of GSoC project - Vert.x Blueprint Todo Backend Application, including both English version and Chinese version.

I've tested generating the blog in local and everything is ok but there is a problem that the generator cannot generate the correct directory name of the Chinese version document.

### CODE REVIEW

**Comment by michel-kraemer** [comment]
I've quickly browsed over this pull request. The English blog post seems to be OK. Thanks for that! I couldn't check the Chinese version though :-)

I'd like to discuss the following two points:

* IMHO the blog post could be split up into two or three instalments. I guess, otherwise, nobody will read such a long post and that would be a pity. What do you think?
* We normally don't have multi-lingual content on the web site. While I like the English post, I think we can remove the Chinese one. If necessary it could probably be posted at http://vertxer.org/ instead of here. @vietj and @cescoffier what do you think about this?
* I'm unsure if we need a "yet-another-introduction-to-vertx" section in the blog post. I think we should start with the actual content. Readers of this blog should be familiar with what Vert.x is.

**Comment by sczyh30** [comment]
Hi Michel, thanks for review! I've taken your advice and split the blog post into two parts as well as removed the `introduction-to-vertx` section. And I've also removed the Chinese version and I'll post it on Vert.x China User Group :-)

And is it OK if we translate the contents of Vert.x Website into Chinese and put it into a path(e.g. `http://vertx.io/cn`?

**Comment by michel-kraemer** [comment]
Thanks for the changes. I'll review them later.

> And is it OK if we translate the contents of Vert.x Website into Chinese and put it into a path

Offering this is very kind of you. However, I think this would be too much work and maintaining the Chinese version and keep it up to date constantly would be no less so. I would advise to only keep an English version. That's my humble opinion, but there might of course be others...

**Comment by pmlopes** [comment]
The Chinese content is a task of gsoc and we can't throw it away. It is true that the site does not have multi lingual content but it might change.

**Comment by michel-kraemer** [comment]
I see. I didn't know that.

Don't get me wrong. I'm not against it, I just thought that a single Chinese post would probably be out of place.

**Comment by vietj** [comment]
we should have made the gsoc stuff more explained/advertised on vertx-dev

**Comment by sczyh30** [comment]
Close this as the blueprint blog post has been published.

**Pull request closed without merging**
