### PR TITLE
Add Adnato logo

### PR DESCRIPTION
**Pull request by riperez**

### CODE REVIEW

**Comment by cescoffier** [comment]
Hi, thanks ! 

The link target a site under construction. Do you know then the web site would be available ?

**Comment by riperez** [comment]
Sorry it caught you in the middle of a web site redesign. I will let you know as soon as it's live again.

**Comment by cescoffier** [comment]
Thanks. The logo is perfect (thanks for providing the logo and the metadata)

**Comment by michel-kraemer** [comment]
@riperez It seems the website is still under construction. Any news?

**Comment by riperez** [comment]
The website will not be ready soon, sorry about that. Let's put the PR in standby for the moment. We do a extensively use of Vert.x though ;)

**Pull request closed without merging**
