### PR TITLE
Add download page

### PR DESCRIPTION
**Pull request by michel-kraemer**
I'm always confused when I click the download link and am redirected to Bintray. A dedicated download page improves user experience.

### CODE REVIEW

**Comment by cescoffier** [comment]
it looks it involves extra steps during the release process.

**Comment by cescoffier** [comment]
We should extract the required data from Maven Central to avoid having to update the page after each release.

**Comment by michel-kraemer** [comment]
OK. I'll see what I can do.

**Comment by michel-kraemer** [comment]
I guess something like `gulp update-contributors` would be best? I suppose you want to trigger updating the download page manually and not having it updated each time the site is built, right?

**Comment by michel-kraemer** [comment]
@cescoffier Please review again. I think I found a reasonable way to update the page automatically. The only caveat is that file names of full, min and html distribution must always adhere to the same pattern. This hasn't been the case for previous versions, but IMHO it should be in the future. WDYT?

**Comment by cescoffier** [comment]
I've tried it, but got a " Error: ENOENT: no such file or directory, open 'target/distribution-info/distribution-info.json'". Maybe this file should be in "src" as the contributors one ?

**Comment by michel-kraemer** [comment]
Oops! Sorry. My fault. I fixed the bug and rebased the branch against master. Please review again. Thanks!

**Comment by cescoffier** [comment]
It's live ! 

I've made some changes to add the "alternative" way to install the distribution (we have lots of way now...).

Thanks, it's awesome.

**Comment by michel-kraemer** [comment]
Looks great! Thanks!

**Pull request merged**
