### PR TITLE
add logo of leap.as

### PR DESCRIPTION
**Pull request by stream1984**
add our company logo

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Thanks for the PR. The logo is really small (compared to the others). Can you make it a bit larger so the font is at least 45px? Besides, it is out of center.

**Comment by purplefox** [comment]
Hi @stream1984 - any updates on this? We would like to get your logo up, but the one you provided is very small so won't look too nice if we scale it up.

**Comment by purplefox** [comment]
Hi @stream1984 any further updates?

**Comment by michel-kraemer** [comment]
This issue is really old and we haven't heard back from the original poster since more than three months now. I'm going to close it. @stream1984 If you still want to add your logo, please let us know. We will be more than happy to add it if you can provide it in the right resolution.

**Pull request closed without merging**
