### PR TITLE
Added link to conf-schedule repo

### PR DESCRIPTION
**Pull request by slinkydeveloper**

### CODE REVIEW

**Comment by vietj** [comment]
for now I would not add it to the navigation but rahter in Materials maybe

**Comment by vietj** [comment]
my motiviation is that the topnav is already crowded

**Comment by vietj** [comment]
I think you should send an email on vertx-dev to discuss the best place to add it on web-site

**Comment by michel-kraemer** [comment]
Just curious: What's the result of the discussion? Should we follow up on this or close the pull request?

**Comment by vietj** [comment]
whats your opinion on this cosmetic/usability problem ?

**Comment by slinkydeveloper** [comment]
I agree to put it under Community section

**Comment by vietj** [comment]
I'm for it as well

**Pull request closed without merging**
