### PR TITLE
Remove extra "V" typo

### PR DESCRIPTION
**Pull request by k-mack**
Correct "VVert.x" to "Vert.x" in Vert.x-Web documentation.

### CODE REVIEW

**Comment by cescoffier** [comment]
Thanks !

**Comment by michel-kraemer** [comment]
I received a similar report by email. Has this already been published?

**Comment by cescoffier** [comment]
The change has been merged, but the changes have been made in the vert.x web project. This updated documentation has not been republished. 

As we are expecting a new release soon, that would fix this issue (publish the updated documentation), I didn't use the overriding feature to fix the issue on the web site. I can do it, I generally do, but as this is not critical (that's debatable of course), I was just waiting the next release (3.3.4).

**Comment by michel-kraemer** [comment]
Good to know. Thanks for the feedback.

**Pull request merged**
