### PR TITLE
Adding logos ...

### PR DESCRIPTION
**Pull request by carlobertuccini**
Hi,
following the pr with lastminute, rumbo and volagratis logos.

cheers

### CODE REVIEW

**Comment by tsegismont** [comment]
Have you checked thje result? What does the page look like with white font
and image logos?

2017-01-05 17:42 GMT+01:00 carlobertuccini <notifications@github.com>:

**Comment by carlobertuccini** [comment]
Hi,
sure I did. It looks good to me -- tried with both Chrome and Firefox.
Following couple of screenshots from local-running gulp server 

chrome_home
chrome_whoisusing

**Comment by cescoffier** [comment]
Thanks,

Looks good to me. I've updated the web site.

**Comment by michel-kraemer** [comment]
@carlobertuccini 

Thank you for providing your company logos for the "Who's using Vert.x" section on the Vert.x website. We are currently updating the website for Vert.x 4. For this, we are looking for up-to-date versions of all company logos in full color and high resolution.

If you still want to be listed on the Vert.x website, can you please create a pull request in the new website repository (https://github.com/vertx-web-site/vertx-web-site/pulls) and send us your logos as **SVG files**? Just include the logos in the pull request - I'll do the rest. Thank you so much! 😊

**Pull request merged**
